# Generated by Django 4.2.7 on 2023-12-03 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excelinterface', '0002_alter_databasemodel_graph_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingmodel',
            name='csv',
        ),
        migrations.AlterField(
            model_name='inportdatamodel',
            name='mapping_id',
            field=models.ForeignKey(help_text='mapping id', on_delete=django.db.models.deletion.CASCADE, related_name='import_mapping_id', to='excelinterface.mappingmodel'),
        ),
        migrations.CreateModel(
            name='ExportDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.JSONField(default=dict, help_text='csv data', null=True)),
                ('query', models.TextField()),
                ('mapping_id', models.ForeignKey(help_text='mapping id', on_delete=django.db.models.deletion.CASCADE, related_name='export_mapping_id', to='excelinterface.mappingmodel')),
            ],
        ),
    ]
