# Generated by Django 4.2.7 on 2023-12-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelinterface', '0003_remove_mappingmodel_csv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingmodel',
            name='name',
            field=models.CharField(default='default', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
