# Generated by Django 4.2.7 on 2023-12-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelinterface', '0004_mappingmodel_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InportDataModel',
            new_name='ImportDataModel',
        ),
        migrations.AddField(
            model_name='mappingmodel',
            name='predicate_var_to_val',
            field=models.JSONField(default=dict, help_text='mapping between the excel variables and actual rdf values', null=True),
        ),
    ]
