# Generated by Django 4.2.7 on 2023-12-04 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excelinterface', '0005_rename_inportdatamodel_importdatamodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importdatamodel',
            name='mapping_id',
        ),
        migrations.AddField(
            model_name='importdatamodel',
            name='export_id',
            field=models.ForeignKey(default=1, help_text='export id', on_delete=django.db.models.deletion.CASCADE, related_name='export_id', to='excelinterface.exportdatamodel'),
            preserve_default=False,
        ),
    ]
