# Generated by Django 4.2.7 on 2023-12-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelinterface', '0006_remove_importdatamodel_mapping_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportdatamodel',
            name='csv',
            field=models.JSONField(default=list, help_text='csv data', null=True),
        ),
        migrations.AlterField(
            model_name='importdatamodel',
            name='csv',
            field=models.JSONField(default=list, help_text='csv data', null=True),
        ),
    ]
