# Generated by Django 4.2.7 on 2023-12-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelinterface', '0008_alter_exportdatamodel_csv_alter_importdatamodel_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingmodel',
            name='is_custom_mapping',
            field=models.BooleanField(default=False),
        ),
    ]
